const fs = require('fs');
const path = require('path');

// Target file
const filePath = path.join(__dirname, 'src', 'data', 'vocabExtraData2.js');

// 1. ORIGINAL SUCCESS MINDSET TOPIC (100 WORDS) - CORRECTED TEMPLATE EXAMPLES TO BE NATURAL
const successWordsRaw = [
  ["achieve", "đạt được", "(v)", "/əˈtʃiːv/", "accomplish; attain", "fail; give up", "With enough effort, you can achieve your goals.", "Với đủ nỗ lực, bạn có thể đạt được mục tiêu của mình.", "B1"],
  ["goal", "mục tiêu", "(n)", "/ɡəʊl/", "target; objective", "aimlessness", "Set a clear goal for your career.", "Hãy đặt một mục tiêu rõ ràng cho sự nghiệp của bạn.", "B1"],
  ["success", "thành công", "(n)", "/səkˈses/", "triumph; victory", "failure; defeat", "Hard work is the key to success.", "Chăm chỉ là chìa khóa dẫn đến thành công.", "B1"],
  ["effort", "nỗ lực", "(n)", "/ˈef.ət/", "attempt; endeavor", "laziness; apathy", "She put a lot of effort into her studies.", "Cô ấy đã dành nhiều nỗ lực cho việc học của mình.", "B1"],
  ["motivation", "động lực", "(n)", "/ˌməʊ.tɪˈveɪ.ʃən/", "inspiration; drive", "discouragement", "What is your main motivation for learning English?", "Động lực chính để bạn học tiếng Anh là gì?", "B1"],
  ["inspire", "truyền cảm hứng", "(v)", "/ɪnˈspaɪər/", "encourage; motivate", "discourage", "My parents inspire me to work harder.", "Cha mẹ truyền cảm hứng cho tôi làm việc chăm chỉ hơn.", "B1"],
  ["overcome", "vượt qua", "(v)", "/ˌəʊ.vəˈkʌm/", "conquer; defeat", "surrender; yield", "We must overcome many difficulties.", "Chúng ta phải vượt qua nhiều khó khăn.", "B1"],
  ["obstacle", "trở ngại", "(n)", "/ˈɒb.stə.kəl/", "barrier; hurdle", "advantage", "Fear is the biggest obstacle to success.", "Nỗi sợ hãi là trở ngại lớn nhất đối với thành công.", "B1"],
  ["determination", "sự quyết tâm", "(n)", "/dɪˌtɜː.mɪˈneɪ.ʃən/", "resolve; willpower", "hesitation", "She showed great determination to win.", "Cô ấy đã thể hiện sự quyết tâm lớn để giành chiến thắng.", "B2"],
  ["focus", "tập trung", "(v)", "/ˈfəʊ.kəs/", "concentrate", "distract", "You need to focus on your exam.", "Bạn cần tập trung vào kỳ thi của mình.", "B1"],
  ["mindset", "tư duy", "(n)", "/ˈmaɪnd.set/", "mentality; attitude", "-", "A positive mindset helps you solve problems.", "Một tư duy tích cực giúp bạn giải quyết vấn đề.", "B2"],
  ["growth", "sự phát triển", "(n)", "/ɡrəʊθ/", "development; expansion", "decline; reduction", "The company experienced rapid growth.", "Công ty đã trải qua sự phát triển nhanh chóng.", "B1"],
  ["habit", "thói quen", "(n)", "/ˈhæb.ɪt/", "routine; pattern", "-", "Reading books is a good habit.", "Đọc sách là một thói quen tốt.", "A2"],
  ["consistency", "sự kiên định/nhất quán", "(n)", "/kənˈsɪs.tən.si/", "steadiness; reliability", "inconsistency", "Consistency is key to forming a habit.", "Sự kiên định là chìa khóa để hình thành thói quen.", "B2"],
  ["discipline", "kỷ luật", "(n)", "/ˈdɪs.ə.plɪn/", "control; regulation", "chaos; mess", "Self-discipline is important for success.", "Tính tự kỷ luật rất quan trọng đối với thành công.", "B2"],
  ["resilience", "sự kiên cường", "(n)", "/rɪˈzɪl.jəns/", "toughness; flexibility", "fragility; vulnerability", "Resilience helps you bounce back from failure.", "Sự kiên cường giúp bạn đứng dậy sau thất bại.", "C1"],
  ["progress", "tiến bộ", "(n)", "/ˈprəʊ.ɡres/", "advancement; improvement", "regression", "He is making good progress in school.", "Cậu ấy đang tiến bộ tốt ở trường.", "B1"],
  ["potential", "tiềm năng", "(n)", "/pəˈten.ʃəl/", "capability; possibility", "inability", "Every student has the potential to succeed.", "Mỗi học sinh đều có tiềm năng để thành công.", "B2"],
  ["strategy", "chiến lược", "(n)", "/ˈstræt.ə.dʒi/", "plan; approach", "-", "We need a new business strategy.", "Chúng ta cần một chiến lược kinh doanh mới.", "B2"],
  ["execute", "thực thi", "(v)", "/ˈek.sɪ.kjuːt/", "implement; perform", "abandon; neglect", "It is time to execute our plan.", "Đã đến lúc thực thi kế hoạch của chúng ta.", "C1"],
  ["vision", "tầm nhìn", "(n)", "/ˈvɪʒ.ən/", "foresight; imagination", "blindness", "The leader had a clear vision for the future.", "Người lãnh đạo có tầm nhìn rõ ràng cho tương lai.", "B2"],
  ["ambition", "hoài bão", "(n)", "/æmˈbɪʃ.ən/", "aspiration; desire", "laziness", "His ambition is to become a doctor.", "Hoài bão của anh ấy là trở thành bác sĩ.", "B2"],
  ["courage", "lòng dũng cảm", "(n)", "/ˈkʌr.ɪdʒ/", "bravery; valor", "cowardice; fear", "It takes courage to speak the truth.", "Cần có lòng dũng cảm để nói ra sự thật.", "B1"],
  ["dedication", "sự cống hiến", "(n)", "/ˌded.ɪˈkeɪ.ʃən/", "commitment; devotion", "apathy; indifference", "Success requires hard work and dedication.", "Thành công đòi hỏi sự chăm chỉ và cống hiến.", "B2"],
  ["empower", "trao quyền", "(v)", "/ɪmˈpaʊər/", "authorize; enable", "weaken; suppress", "Education empowers people.", "Giáo dục trao quyền cho con người.", "B2"],
  ["fearless", "không sợ hãi", "(adj)", "/ˈfɪə.ləs/", "brave; bold", "fearful; timid", "She is a fearless explorer.", "Cô ấy là một nhà thám hiểm không sợ hãi.", "C1"],
  ["grateful", "biết ơn", "(adj)", "/ˈɡreɪt.fəl/", "thankful; appreciative", "ungrateful", "I am grateful for your help.", "Tôi biết ơn vì sự giúp đỡ của bạn.", "B1"],
  ["hardship", "sự gian khổ", "(n)", "/ˈhɑːd.ʃɪp/", "difficulty; suffering", "comfort; ease", "They overcame every hardship together.", "Họ đã cùng nhau vượt qua mọi gian khổ.", "B2"],
  ["innovate", "đổi mới", "(v)", "/ˈɪn.ə.veɪt/", "invent; modernize", "stagnate", "Companies must innovate to survive.", "Các công ty phải đổi mới để sinh tồn.", "C1"],
  ["journey", "hành trình", "(n)", "/ˈdʒɜː.ni/", "trip; expedition", "-", "Life is a long journey.", "Cuộc sống là một hành trình dài.", "B1"],
  ["knowledge", "kiến thức", "(n)", "/ˈnɒl.ɪdʒ/", "understanding; wisdom", "ignorance", "Knowledge is power.", "Kiến thức là sức mạnh.", "A2"],
  ["leadership", "sự lãnh đạo", "(n)", "/ˈliː.də.ʃɪp/", "guidance; management", "subordination", "Good leadership inspires teamwork.", "Sự lãnh đạo tốt truyền cảm hứng cho tinh thần đồng đội.", "B2"],
  ["mastery", "sự thành thạo", "(n)", "/ˈmɑː.stər.i/", "expertise; proficiency", "incompetence", "He achieved mastery of the English language.", "Anh ấy đã đạt được sự thành thạo tiếng Anh.", "C1"],
  ["navigate", "điều hướng/vượt qua", "(v)", "/ˈnæv.ɪ.ɡeɪt/", "steer; guide", "get lost", "He helped us navigate the system.", "Anh ấy đã giúp chúng tôi điều hướng hệ thống.", "B2"],
  ["optimism", "sự lạc quan", "(n)", "/ˈɒp.tɪ.mɪ.zəm/", "hopefulness; positivity", "pessimism", "Optimism helps you stay happy.", "Sự lạc quan giúp bạn duy trì hạnh phúc.", "B2"],
  ["passion", "đam mê", "(n)", "/ˈpæʃ.ən/", "enthusiasm; zeal", "indifference", "She has a passion for teaching.", "Cô ấy có niềm đam mê với việc giảng dạy.", "B1"],
  ["quality", "chất lượng", "(n)", "/ˈkwɒl.ə.ti/", "excellence; standard", "inferiority", "We focus on product quality.", "Chúng tôi tập trung vào chất lượng sản phẩm.", "B1"],
  ["reflect", "phản chiếu/ngẫm nghĩ", "(v)", "/rɪˈflekt/", "think; ponder", "ignore", "Take time to reflect on your day.", "Hãy dành thời gian để ngẫm nghĩ về một ngày của bạn.", "B2"],
  ["skill", "kỹ năng", "(n)", "/skɪl/", "ability; talent", "clumsiness", "Cooking is a useful life skill.", "Nấu ăn là một kỹ năng sống hữu ích.", "A2"],
  ["talent", "tài năng", "(n)", "/ˈtæl.ənt/", "gift; aptitude", "weakness", "She has a natural talent for music.", "Cô ấy có tài năng thiên bẩm về âm nhạc.", "B1"],
  ["unique", "độc đáo", "(adj)", "/juːˈniːk/", "distinct; exclusive", "common; ordinary", "Everyone has a unique fingerprint.", "Mỗi người đều có một dấu vân tay độc đáo.", "B1"],
  ["value", "giá trị", "(n)", "/ˈvæl.juː/", "worth; importance", "worthlessness", "Education has great value.", "Giáo dục có giá trị to lớn.", "B1"],
  ["wisdom", "trí tuệ", "(n)", "/ˈwɪz.dəm/", "insight; intelligence", "foolishness", "The old man shared his wisdom with us.", "Ông cụ đã chia sẻ trí tuệ của mình với chúng tôi.", "B2"],
  ["yield", "mang lại/tạo ra", "(v)", "/jiːld/", "produce; generate", "resist", "The investment will yield good results.", "Khoản đầu tư sẽ mang lại kết quả tốt.", "C1"],
  ["zeal", "sự nhiệt huyết", "(n)", "/ziːl/", "passion; fervor", "apathy", "He worked with great zeal.", "Anh ấy đã làm việc với sự nhiệt huyết lớn.", "C1"],
  ["adapt", "thích nghi", "(v)", "/əˈdæpt/", "adjust; modify", "refuse", "You must adapt to the cold weather.", "Bạn phải thích nghi với thời tiết lạnh.", "B2"],
  ["believe", "tin tưởng", "(v)", "/bɪˈliːv/", "trust; have faith", "doubt; disbelieve", "You must believe in yourself.", "Bạn phải tin tưởng vào bản thân mình.", "A2"],
  ["commit", "cam kết", "(v)", "/kəˈmɪt/", "pledge; promise", "renege", "We commit to improving our service.", "Chúng tôi cam kết cải thiện dịch vụ của mình.", "B2"],
  ["develop", "phát triển", "(v)", "/dɪˈvel.əp/", "grow; evolve", "shrink; halt", "Children develop skills quickly.", "Trẻ em phát triển các kỹ năng một cách nhanh chóng.", "B1"],
  ["evolve", "tiến hóa/phát triển", "(v)", "/ɪˈvɒlv/", "develop; advance", "regress", "Technologies evolve over time.", "Công nghệ phát triển theo thời gian.", "C1"],
  ["flourish", "phát triển mạnh mẽ", "(v)", "/ˈflʌr.ɪʃ/", "thrive; prosper", "wither; decline", "The plants flourish in the sunlight.", "Cây cối phát triển mạnh mẽ dưới ánh nắng mặt trời.", "C1"],
  ["generate", "tạo ra", "(v)", "/ˈdʒen.ə.reɪt/", "create; produce", "destroy", "This project will generate new jobs.", "Dự án này sẽ tạo ra những công việc mới.", "B2"],
  ["hustle", "hối hả/chăm chỉ", "(v)", "/ˈhʌs.əl/", "work hard; rush", "relax; dawdle", "You need to hustle to meet the deadline.", "Bạn cần khẩn trương để kịp thời hạn.", "B2"],
  ["improve", "cải thiện", "(v)", "/ɪmˈpruːv/", "enhance; upgrade", "worsen", "Practice will improve your English.", "Luyện tập sẽ cải thiện tiếng Anh của bạn.", "A2"],
  ["justify", "biện minh/chứng minh", "(v)", "/d\u0292\u028cs.t\u026a.fa\u026a/", "defend; explain", "condemn", "You must justify your decisions.", "Bạn phải chứng minh cho các quyết định của mình.", "C1"],
  ["kindle", "thắp sáng/khơi gợi", "(v)", "/ˈkɪn.dəl/", "ignite; spark", "extinguish", "The book kindled her interest in science.", "Cuốn sách đã khơi gợi sự hứng thú của cô ấy với khoa học.", "C2"],
  ["learn", "học hỏi", "(v)", "/lɜːn/", "study; acquire", "ignore", "I want to learn how to play guitar.", "Tôi muốn học cách chơi đàn ghi-ta.", "A1"],
  ["manifest", "biểu hiện/thể hiện", "(v)", "/ˈmæn.ɪ.fest/", "demonstrate; reveal", "hide; conceal", "His stress manifested as a headache.", "Sự căng thẳng của anh ấy biểu hiện bằng việc đau đầu.", "C1"],
  ["nurture", "nuôi dưỡng", "(v)", "/ˈnɜː.tʃər/", "foster; care for", "neglect", "Parents nurture their children's dreams.", "Cha mẹ nuôi dưỡng ước mơ của con cái.", "B2"],
  ["organize", "tổ chức", "(v)", "/ˈɔː.ɡən.aɪz/", "arrange; structure", "disorganize", "Let's organize a school party.", "Hãy tổ chức một buổi tiệc trường học.", "B1"],
  ["persevere", "kiên trì", "(v)", "/ˌpɜː.sɪˈvɪər/", "persist; keep on", "give up; quit", "If you persevere, you will succeed.", "Nếu bạn kiên trì, bạn sẽ thành công.", "B2"],
  ["question", "đặt câu hỏi", "(v)", "/ˈkwes.tʃən/", "inquire; doubt", "accept", "Don't be afraid to question things.", "Đừng ngại đặt câu hỏi về mọi thứ.", "A2"],
  ["reinvent", "tái tạo/đổi mới", "(v)", "/ˌriː.ɪnˈvent/", "recreate; remake", "maintain", "He chose to reinvent himself after retirement.", "Ông ấy chọn đổi mới bản thân sau khi nghỉ hưu.", "C1"],
  ["strive", "phấn đấu", "(v)", "/straɪv/", "aim; attempt", "surrender", "We strive to satisfy our clients.", "Chúng tôi phấn đấu để làm hài lòng khách hàng.", "B2"],
  ["transform", "biến đổi", "(v)", "/trænsˈfɔːm/", "change; alter", "preserve", "A caterpillar transforms into a butterfly.", "Sâu bướm biến đổi thành một con bướm.", "B2"],
  ["unleash", "giải phóng/bung tỏa", "(v)", "/ʌnˈliːʃ/", "release; free", "restrain", "He unleashed his creativity in the drawing.", "Anh ấy đã giải phóng sự sáng tạo của mình trong bức vẽ.", "C1"],
  ["visualize", "hình dung", "(v)", "/ˈvɪʒ.u.ə.laɪz/", "imagine; envision", "ignore", "Visualize your goal to stay motivated.", "Hãy hình dung mục tiêu của bạn để giữ động lực.", "B2"],
  ["win", "chiến thắng", "(v)", "/wɪn/", "succeed; triumph", "lose", "They want to win the soccer match.", "Họ muốn giành chiến thắng trong trận đấu bóng đá.", "A1"],
  ["xenial", "hiếu khách/thân thiện", "(adj)", "/ˈziː.ni.əl/", "hospitable; friendly", "unfriendly", "The locals are xenial towards tourists.", "Người dân địa phương rất hiếu khách với khách du lịch.", "C2"],
  ["yearn", "khao khát", "(v)", "/jɜːn/", "desire; long for", "despise", "Many people yearn for peace.", "Nhiều người khao khát hòa bình.", "C1"],
  ["zenith", "đỉnh cao", "(n)", "/ˈzen.ɪθ/", "peak; pinnacle", "bottom; nadir", "He was at the zenith of his career.", "Anh ấy đã ở đỉnh cao của sự nghiệp.", "C2"],
  ["action", "hành động", "(n)", "/ˈæk.ʃən/", "deed; activity", "inaction", "Actions speak louder than words.", "Hành động có giá trị hơn lời nói.", "A2"],
  ["balance", "cân bằng", "(n)", "/ˈbæl.əns/", "equilibrium; stability", "instability", "It is important to keep a work-life balance.", "Giữ cân bằng cuộc sống và công việc rất quan trọng.", "B1"],
  ["character", "tính cách", "(n)", "/ˈkær.ək.tər/", "personality; nature", "-", "Hard times build strong character.", "Những lúc khó khăn sẽ xây dựng tính cách mạnh mẽ.", "B1"],
  ["dream", "ước mơ", "(n)", "/driːm/", "fantasy; vision", "reality", "Follow your dream no matter what.", "Hãy theo đuổi ước mơ của bạn dù có thế nào.", "A1"],
  ["energy", "năng lượng", "(n)", "/ˈen.ə.dʒi/", "vitality; power", "lethargy", "Children have a lot of energy.", "Trẻ em có rất nhiều năng lượng.", "A2"],
  ["freedom", "tự do", "(n)", "/ˈfriː.dəm/", "liberty; independence", "captivity; slavery", "Freedom of speech is a basic right.", "Tự do ngôn luận là một quyền cơ bản.", "B1"],
  ["grace", "sự duyên dáng/tử tế", "(n)", "/ɡreɪs/", "elegance; charm", "clumsiness", "She danced with grace and beauty.", "Cô ấy nhảy múa với sự duyên dáng và vẻ đẹp.", "B2"],
  ["hope", "hy vọng", "(n)", "/həʊp/", "optimism; wish", "despair", "Where there is life, there is hope.", "Còn sống là còn hy vọng.", "A1"],
  ["intuition", "trực giác", "(n)", "/ˌɪn.tʃuˈɪʃ.ən/", "instinct; feeling", "reasoning", "Trust your intuition when making a choice.", "Hãy tin vào trực giác của bạn khi đưa ra lựa chọn.", "C1"],
  ["joy", "niềm vui", "(n)", "/dʒɔɪ/", "happiness; delight", "sorrow", "Children bring joy to the family.", "Trẻ em mang lại niềm vui cho gia đình.", "A2"],
  ["karma", "luật nhân quả", "(n)", "/ˈkɑː.mə/", "fate; destiny", "-", "Good deeds bring good karma.", "Việc thiện đem lại nhân quả tốt.", "C1"],
  ["logic", "lý lẽ/logic", "(n)", "/ˈlɒdʒ.ɪk/", "reason; sense", "irrationality", "His logic was simple and clear.", "Lý lẽ của anh ấy rất đơn giản và rõ ràng.", "B1"],
  ["mindfulness", "sự chánh niệm", "(n)", "/ˈmaɪnd.fəl.nəs/", "awareness; attention", "distraction", "Mindfulness helps reduce daily stress.", "Sự chánh niệm giúp giảm căng thẳng hàng ngày.", "B2"],
  ["network", "mạng lưới/kết nối", "(n)", "/ˈnet.wɜːk/", "connection; web", "isolation", "Build a professional network.", "Hãy xây dựng một mạng lưới chuyên nghiệp.", "B1"],
  ["opportunity", "cơ hội", "(n)", "/ˌɒp.əˈtʃuː.nə.ti/", "chance; prospect", "disadvantage", "Take every opportunity to practice English.", "Hãy tận dụng mọi cơ hội để luyện tập tiếng Anh.", "B1"],
  ["purpose", "mục đích", "(n)", "/ˈpɜː.pəs/", "aim; intention", "meaninglessness", "What is the purpose of this meeting?", "Mục đích của cuộc họp này là gì?", "B1"],
  ["quiet", "sự tĩnh lặng", "(adj)", "/ˈkwaɪ.ət/", "silence; calm", "noise", "I need a quiet place to study.", "Tôi cần một nơi yên tĩnh để học tập.", "A1"],
  ["respect", "sự tôn trọng", "(n)", "/rɪˈspekt/", "esteem; honor", "disrespect", "Respect other people's privacy.", "Hãy tôn trọng quyền riêng tư của người khác.", "A2"],
  ["strength", "sức mạnh", "(n)", "/streŋθ/", "power; might", "weakness", "Union is strength.", "Đoàn kết là sức mạnh.", "B1"],
  ["trust", "niềm tin", "(n)", "/trʌst/", "faith; belief", "distrust", "Trust is the base of any relationship.", "Niềm tin là nền tảng của mọi mối quan hệ.", "A2"],
  ["unity", "sự đoàn kết", "(n)", "/ˈjuː.nə.ti/", "harmony; solidarity", "division", "Unity makes us strong.", "Sự đoàn kết giúp chúng ta mạnh mẽ.", "B2"],
  ["vitality", "sức sống", "(n)", "/vaɪˈtæl.ə.ti/", "energy; vigor", "lethargy", "Exercise keeps your body full of vitality.", "Tập thể dục giữ cho cơ thể bạn tràn đầy sức sống.", "C1"],
  ["wealth", "sự giàu có", "(n)", "/welθ/", "richness; prosperity", "poverty", "Health is wealth.", "Sức khỏe là sự giàu có.", "B1"],
  ["experience", "kinh nghiệm/trải nghiệm", "(n)", "/ɪkˈspɪə.ri.əns/", "knowledge; practice", "inexperience", "Experience is the best teacher.", "Trải nghiệm là người thầy tốt nhất.", "A2"],
  ["youth", "tuổi trẻ", "(n)", "/juːθ/", "youngness; prime", "old age", "Make the best of your youth.", "Hãy tận dụng tốt nhất tuổi trẻ của bạn.", "B1"],
  ["zealous", "nhiệt tình", "(adj)", "/ˈzel.əs/", "enthusiastic; eager", "apathetic", "He is a zealous supporter of our team.", "Anh ấy là một cổ động viên nhiệt tình của đội chúng tôi.", "C1"],
  ["abundant", "dồi dào", "(adj)", "/əˈbʌn.dənt/", "plentiful; ample", "scarce", "We have abundant natural resources.", "Chúng ta có nguồn tài nguyên thiên nhiên dồi dào.", "B2"],
  ["brave", "dũng cảm", "(adj)", "/breɪv/", "courageous; bold", "cowardly", "The brave firefighter saved the child.", "Người lính cứu hỏa dũng cảm đã cứu em bé.", "A2"],
  ["calm", "bình tĩnh", "(adj)", "/kɑːm/", "peaceful; tranquil", "anxious; chaotic", "Try to stay calm during the test.", "Hãy cố gắng giữ bình tĩnh trong suốt bài thi.", "B1"],
  ["grit", "sự bền gan", "(n)", "/ɡrɪt/", "courage; determination", "cowardice", "Success takes passion and grit.", "Thành công cần có đam mê và sự bền gan.", "B2"]
];

// 2. NEW BASIC TOPIC: SCHOOL LIFE (100 WORDS) - LEVEL A1-A2
const schoolWordsRaw = [
  ["pencil", "bút chì", "(n)", "/ˈpen.səl/", "graphite pen", "-", "I always write my sketches with a pencil.", "Tôi luôn vẽ phác thảo bằng bút chì.", "A1"],
  ["notebook", "vở/sổ tay", "(n)", "/ˈnəʊt.bʊk/", "notepad; journal", "-", "Write your homework down in your notebook.", "Hãy ghi bài tập về nhà vào vở của bạn.", "A1"],
  ["teacher", "giáo viên", "(n)", "/ˈtiː.tʃər/", "instructor; educator", "-", "The teacher explains the grammar clearly.", "Giáo viên giải thích ngữ pháp rất rõ ràng.", "A1"],
  ["student", "học sinh/sinh viên", "(n)", "/ˈstjuː.dənt/", "learner; pupil", "-", "She is a hard-working student.", "Cô ấy là một học sinh chăm chỉ.", "A1"],
  ["classroom", "lớp học", "(n)", "/ˈklɑːs.ruːm/", "study room", "-", "Our classroom has a big white board.", "Lớp học của chúng tôi có một chiếc bảng trắng lớn.", "A1"],
  ["schoolbag", "cặp sách", "(n)", "/ˈskuːl.bæɡ/", "backpack", "-", "Put your textbooks inside your schoolbag.", "Hãy cất sách giáo khoa vào trong cặp sách.", "A1"],
  ["whiteboard", "bảng trắng", "(n)", "/ˈwaɪt.bɔːd/", "board", "-", "The teacher wrote the new words on the whiteboard.", "Giáo viên đã viết từ mới lên bảng trắng.", "A1"],
  ["textbook", "sách giáo khoa", "(n)", "/ˈtekst.bʊk/", "study book", "-", "Open your textbook to page forty.", "Hãy mở sách giáo khoa ra trang bốn mươi.", "A1"],
  ["ruler", "thước kẻ", "(n)", "/ˈruː.lər/", "straightedge", "-", "Use a ruler to draw a straight line.", "Sử dụng thước kẻ để vẽ một đường thẳng.", "A1"],
  ["eraser", "cục tẩy", "(n)", "/ɪˈreɪ.zər/", "rubber", "-", "Can I borrow your eraser for a second?", "Tôi có thể mượn cục tẩy của bạn một lát không?", "A1"],
  ["library", "thư viện", "(n)", "/ˈlaɪ.brər.i/", "book room", "-", "I go to the library to study in quiet.", "Tôi đến thư viện để học bài trong không gian yên tĩnh.", "A1"],
  ["lesson", "bài học", "(n)", "/ˈles.ən/", "class; session", "-", "Today's lesson is about active voice.", "Bài học hôm nay nói về thể chủ động.", "A1"],
  ["homework", "bài tập về nhà", "(n)", "/ˈhəʊm.wɜːk/", "assignment", "-", "Don't forget to complete your homework.", "Đừng quên hoàn thành bài tập về nhà của bạn.", "A1"],
  ["exam", "kỳ thi", "(n)", "/ɪɡˈzæm/", "test; examination", "-", "We are preparing for the final exam.", "Chúng tôi đang chuẩn bị cho kỳ thi cuối kỳ.", "A2"],
  ["question", "câu hỏi", "(n)", "/ˈkwes.tʃən/", "query", "answer", "If you have a question, raise your hand.", "Nếu bạn có câu hỏi, hãy giơ tay phát biểu.", "A1"],
  ["answer", "câu trả lời", "(n/v)", "/ˈɑːn.sər/", "reply; respond", "question", "She gave a very clever answer.", "Cô ấy đã đưa ra một câu trả lời rất lanh lợi.", "A1"],
  ["learn", "học", "(v)", "/lɜːn/", "study; acquire", "forget", "Children learn languages very quickly.", "Trẻ em học ngôn ngữ rất nhanh.", "A1"],
  ["read", "đọc", "(v)", "/riːd/", "peruse", "-", "I like to read short stories in English.", "Tôi thích đọc truyện ngắn bằng tiếng Anh.", "A1"],
  ["write", "viết", "(v)", "/raɪt/", "jot down", "-", "Please write your full name here.", "Vui lòng viết tên đầy đủ của bạn ở đây.", "A1"],
  ["listen", "nghe", "(v)", "/ˈlɪs.ən/", "hear; pay attention", "ignore", "Listen carefully to the instructions.", "Hãy nghe kỹ hướng dẫn.", "A1"],
  ["speak", "nói", "(v)", "/spiːk/", "talk; converse", "be silent", "She can speak three languages fluently.", "Cô ấy có thể nói trôi chảy ba ngôn ngữ.", "A1"],
  ["desk", "bàn học", "(n)", "/desk/", "table", "-", "Clean your desk before leaving the room.", "Hãy dọn sạch bàn học trước khi rời phòng.", "A1"],
  ["chair", "cái ghế", "(n)", "/tʃeər/", "seat", "-", "Sit down on your chair, please.", "Xin vui lòng ngồi vào ghế của bạn.", "A1"],
  ["computer", "máy tính", "(n)", "/kəmˈpjuː.tər/", "PC; desktop", "-", "We use computers in the IT laboratory.", "Chúng tôi sử dụng máy tính trong phòng thực hành tin học.", "A1"],
  ["classmate", "bạn cùng lớp", "(n)", "/ˈklɑːs.meɪt/", "peer; classmate", "-", "My classmate helped me with math.", "Bạn cùng lớp đã giúp tôi làm bài tập toán.", "A2"],
  ["subject", "môn học", "(n)", "/ˈsʌb.dʒekt/", "discipline", "-", "What is your favorite subject at school?", "Môn học yêu thích nhất của bạn ở trường là gì?", "A1"],
  ["math", "môn toán", "(n)", "/mæθ/", "mathematics", "-", "Math is a very useful subject.", "Môn Toán là một môn học rất hữu ích.", "A1"],
  ["science", "khoa học", "(n)", "/ˈsaɪ.əns/", "scientific study", "-", "We do science experiments on Fridays.", "Chúng tôi làm các thí nghiệm khoa học vào thứ Sáu.", "A2"],
  ["history", "lịch sử", "(n)", "/ˈhɪs.tər.i/", "past events", "-", "Our history class covers world wars.", "Lớp học lịch sử của chúng tôi nói về các cuộc chiến tranh thế giới.", "A2"],
  ["clock", "đồng hồ", "(n)", "/klɒk/", "timepiece", "-", "The school clock shows it is 12 PM.", "Đồng hồ trường học chỉ 12 giờ trưa.", "A1"],
  ["calendar", "lịch", "(n)", "/ˈkæl.ən.dər/", "schedule", "-", "Mark the exam dates on your calendar.", "Hãy đánh dấu các ngày thi trên lịch của bạn.", "A2"],
  ["map", "bản đồ", "(n)", "/mæp/", "chart", "-", "Look at the map to find Tokyo.", "Hãy nhìn vào bản đồ để tìm Tokyo.", "A1"],
  ["break", "giờ nghỉ giải lao", "(n)", "/breɪk/", "recess; pause", "work", "Let's play football during the break.", "Chúng ta hãy chơi đá bóng trong giờ nghỉ giải lao.", "A1"],
  ["playground", "sân chơi", "(n)", "/ˈpleɪ.ɡraʊnd/", "yard", "-", "The kids are running in the playground.", "Trẻ em đang chạy nhảy trên sân chơi.", "A1"],
  ["study", "học tập", "(v/n)", "/ˈstʌd.i/", "learn; revise", "play", "You must study hard for the upcoming test.", "Bạn phải học tập chăm chỉ cho bài kiểm tra sắp tới.", "A1"],
  ["review", "ôn tập", "(v/n)", "/rɪˈvjuː/", "revise; examine", "-", "Review your lessons before sleeping.", "Hãy ôn tập bài học của bạn trước khi đi ngủ.", "A2"],
  ["explain", "giải thích", "(v)", "/ɪkˈspleɪn/", "clarify; describe", "confuse", "Can you explain this rule again?", "Bạn có thể giải thích lại quy tắc này được không?", "A2"],
  ["understand", "hiểu", "(v)", "/ˌʌn.dəˈstænd/", "comprehend; grasp", "misunderstand", "Do you understand what to do now?", "Bạn đã hiểu cần phải làm gì bây giờ chưa?", "A1"],
  ["remember", "nhớ", "(v)", "/rɪˈmem.bər/", "recall", "forget", "Try to remember the vocabulary spelling.", "Hãy cố gắng nhớ cách đánh vần từ vựng.", "A1"],
  ["forget", "quên", "(v)", "/fəˈɡet/", "fail to recall", "remember", "Don't forget to sign the papers.", "Đừng quên ký tên vào giấy tờ.", "A1"],
  ["practice", "luyện tập", "(v/n)", "/ˈpræk.tɪs/", "exercise; drill", "-", "Practice makes perfect, so keep going.", "Luyện tập tạo nên sự hoàn hảo, hãy tiếp tục cố gắng.", "A2"],
  ["group", "nhóm", "(n)", "/ɡruːp/", "team; crew", "individual", "We work in a group of four.", "Chúng tôi làm việc trong một nhóm gồm bốn người.", "A1"],
  ["project", "dự án", "(n)", "/ˈprɒdʒ.ekt/", "assignment; task", "-", "Our group is working on a history project.", "Nhóm chúng tôi đang thực hiện một dự án lịch sử.", "A2"],
  ["presentation", "bài thuyết trình", "(n)", "/ˌprez.ənˈteɪ.ʃən/", "talk; report", "-", "Her presentation was very interesting.", "Bài thuyết trình của cô ấy rất thú vị.", "B1"],
  ["paper", "giấy", "(n)", "/ˈpeɪ.pər/", "sheet", "-", "Write your answers on a clean paper.", "Hãy viết câu trả lời của bạn lên một tờ giấy sạch.", "A1"],
  ["pen", "bút mực", "(n)", "/pen/", "writing tool", "-", "I always write letters with a blue pen.", "Tôi luôn viết thư bằng bút mực màu xanh.", "A1"],
  ["marker", "bút dạ", "(n)", "/ˈmɑː.kər/", "highlighter", "-", "Use a red marker to highlight keywords.", "Hãy dùng bút dạ màu đỏ để làm nổi bật từ khóa.", "A2"],
  ["glue", "hồ dán", "(n/v)", "/ɡluː/", "adhesive", "-", "Use glue to stick the pictures in.", "Sử dụng hồ dán để dán các bức tranh vào.", "A2"],
  ["scissors", "cái kéo", "(n)", "/ˈsɪz.əz/", "cutters", "-", "Be careful when using sharp scissors.", "Hãy cẩn thận khi sử dụng kéo sắc.", "A2"],
  ["dictionary", "từ điển", "(n)", "/ˈdɪk.ʃən.ər.i/", "wordbook", "-", "Look up the new word in the dictionary.", "Hãy tra từ mới trong từ điển.", "A1"],
  ["folder", "kẹp tài liệu", "(n)", "/ˈfəʊl.dər/", "file; binder", "-", "Keep your tests safe in this folder.", "Hãy giữ các bài kiểm tra của bạn an toàn trong kẹp tài liệu này.", "A2"],
  ["test", "bài kiểm tra", "(n/v)", "/test/", "quiz; exam", "-", "We have a vocabulary test tomorrow.", "Chúng tôi có một bài kiểm tra từ vựng vào ngày mai.", "A1"],
  ["score", "điểm số", "(n/v)", "/skɔː/", "mark; points", "-", "She got a perfect score in science.", "Cô ấy đạt điểm số tuyệt đối trong môn khoa học.", "A2"],
  ["grade", "điểm số/lớp học", "(n/v)", "/ɡreɪd/", "mark; level", "-", "He is in the seventh grade.", "Cậu ấy học lớp bảy.", "A2"],
  ["primary", "tiểu học/cơ bản", "(adj)", "/ˈpraɪ.mər.i/", "elementary; basic", "advanced", "Primary school is for children.", "Trường tiểu học dành cho trẻ em.", "A2"],
  ["secondary", "trung học", "(adj)", "/ˈsek.ən.dər.i/", "high school", "primary", "He teaches at a secondary school.", "Thầy ấy giảng dạy tại một trường trung học.", "B1"],
  ["university", "trường đại học", "(n)", "/ˌjuː.nɪˈvɜː.sə.ti/", "institution", "-", "She is studying law at university.", "Cô ấy đang học ngành luật ở trường đại học.", "A2"],
  ["college", "trường cao đẳng/đại học", "(n)", "/ˈkɒl.ɪdʒ/", "school", "-", "He will go to college next year.", "Cậu ấy sẽ học cao đẳng vào năm tới.", "A2"],
  ["course", "khóa học", "(n)", "/kɔːs/", "program; class", "-", "This online course is free for everyone.", "Khóa học trực tuyến này miễn phí cho tất cả mọi người.", "A2"],
  ["class", "lớp học/buổi học", "(n)", "/klɑːs/", "session; course", "-", "Don't be late for English class.", "Đừng đi học muộn lớp tiếng Anh.", "A1"],
  ["smart", "thông minh", "(adj)", "/smɑːt/", "intelligent; bright", "foolish", "He is a smart boy who answers fast.", "Cậu ấy là một cậu bé thông minh trả lời rất nhanh.", "A1"],
  ["clever", "lanh lợi", "(adj)", "/ˈklev.ər/", "smart; resourceful", "stupid", "The dog is clever enough to open doors.", "Chú chó lanh lợi đến mức có thể mở cửa.", "A2"],
  ["hard-working", "chăm chỉ", "(adj)", "/ˌhɑːdˈwɜː.kɪŋ/", "diligent; active", "lazy", "He is very hard-working and focused.", "Cậu ấy rất chăm chỉ và tập trung.", "A2"],
  ["lazy", "lười biếng", "(adj)", "/ˈleɪ.zi/", "idle; inactive", "diligent", "Get out of bed and don't be lazy.", "Hãy bước ra khỏi giường và đừng lười biếng.", "A1"],
  ["quiet", "yên tĩnh", "(adj)", "/ˈkwaɪ.ət/", "silent; calm", "noisy", "Please be quiet in the study hall.", "Vui lòng giữ yên tĩnh trong phòng tự học.", "A1"],
  ["noisy", "ồn ào", "(adj)", "/ˈnɔɪ.zi/", "loud; rowdy", "quiet", "The cafeteria is very noisy at lunchtime.", "Căng tin rất ồn ào vào giờ ăn trưa.", "A1"],
  ["correct", "chính xác", "(adj/v)", "/kəˈrekt/", "right; accurate", "incorrect; wrong", "That is the correct answer.", "Đó là câu trả lời chính xác.", "A2"],
  ["wrong", "sai", "(adj)", "/rɒŋ/", "incorrect; false", "correct", "I answered two questions wrong.", "Tôi đã trả lời sai hai câu hỏi.", "A1"],
  ["simple", "đơn giản", "(adj)", "/ˈsɪm.pəl/", "easy; plain", "complex; hard", "The homework instructions are simple.", "Hướng dẫn làm bài tập về nhà rất đơn giản.", "A2"],
  ["difficult", "khó", "(adj)", "/ˈdɪf.ɪ.kəlt/", "hard; challenging", "easy", "This math problem is too difficult.", "Bài toán này quá khó.", "A1"],
  ["easy", "dễ", "(adj)", "/ˈiː.zi/", "simple; effortless", "difficult", "The exam was very easy, I got ten.", "Kỳ thi rất dễ, tôi đạt điểm mười.", "A1"],
  ["clean", "sạch sẽ", "(adj/v)", "/kliːn/", "tidy; neat", "dirty", "Keep your classroom clean and tidy.", "Hãy giữ lớp học của bạn sạch sẽ và ngăn nắp.", "A1"],
  ["dirty", "bẩn", "(adj)", "/ˈdɜː.ti/", "unclean; messy", "clean", "Don't write on the dirty table.", "Đừng viết lên chiếc bàn bẩn.", "A1"],
  ["help", "giúp đỡ", "(v/n)", "/help/", "assist; support", "hinder", "Can you help me with my project?", "Bạn có thể giúp tôi một tay với dự án này không?", "A1"],
  ["ask", "hỏi", "(v)", "/ɑːsk/", "inquire; request", "answer", "Ask your teacher if you get stuck.", "Hãy hỏi giáo viên nếu bạn bị vướng mắc.", "A1"],
  ["talk", "nói chuyện", "(v/n)", "/tɔːk/", "speak; chat", "be silent", "Don't talk during the lecture.", "Không nói chuyện trong suốt bài giảng.", "A1"],
  ["play", "chơi", "(v)", "/pleɪ/", "have fun", "work", "We play basketball after school.", "Chúng tôi chơi bóng rổ sau giờ học.", "A1"],
  ["draw", "vẽ", "(v)", "/drɔː/", "sketch", "-", "I love to draw houses and trees.", "Tôi thích vẽ những ngôi nhà và hàng cây.", "A1"],
  ["paint", "tô màu/vẽ tranh", "(v/n)", "/peɪnt/", "color; coat", "-", "We will paint our project board green.", "Chúng tôi sẽ tô màu xanh cho bảng dự án.", "A1"],
  ["sing", "hát", "(v)", "/sɪŋ/", "vocalize", "-", "We sing English songs in art class.", "Chúng tôi hát các bài hát tiếng Anh trong lớp nghệ thuật.", "A1"],
  ["dance", "nhảy múa", "(v/n)", "/dɑːns/", "groove", "-", "She likes to dance at school festivals.", "Cô ấy thích nhảy múa tại các lễ hội trường.", "A1"],
  ["bell", "cái chuông", "(n)", "/bel/", "chime", "-", "The school bell rang at exactly 8 AM.", "Chuông trường reo đúng 8 giờ sáng.", "A2"],
  ["backpack", "ba lô", "(n)", "/ˈbæk.pæk/", "rucksack; pack", "-", "He carried a heavy backpack to class.", "Cậu ấy đeo một chiếc ba lô nặng đến lớp.", "A2"],
  ["uniform", "đồng phục", "(n/adj)", "/ˈjuː.nɪ.fɔːm/", "attire", "-", "Students must wear their school uniform.", "Học sinh phải mặc đồng phục trường học.", "A2"],
  ["bus", "xe buýt", "(n)", "/bʌs/", "coach", "-", "I catch the school bus every morning.", "Tôi bắt xe buýt trường học mỗi sáng.", "A1"],
  ["rules", "quy định/nội quy", "(n)", "/ruːlz/", "regulations", "-", "Follow the school rules carefully.", "Hãy tuân thủ các quy định của trường học một cách cẩn thận.", "A2"],
  ["principal", "hiệu trưởng", "(n)", "/ˈprɪn.sə.pəl/", "headmaster", "-", "The principal gave a speech today.", "Hiệu trưởng đã phát biểu ngày hôm nay.", "B1"],
  ["canteen", "căng tin", "(n)", "/kænˈtiːn/", "cafeteria", "-", "We buy lunch at the school canteen.", "Chúng tôi mua bữa trưa tại căng tin trường học.", "A2"],
  ["gym", "phòng thể chất", "(n)", "/dʒɪm/", "gymnasium", "-", "We run laps in the gym.", "Chúng tôi chạy bộ trong phòng thể chất.", "A2"],
  ["art", "mỹ thuật", "(n)", "/ɑːt/", "fine arts", "-", "I enjoy painting in my art class.", "Tôi thích vẽ tranh trong lớp mỹ thuật của mình.", "A1"],
  ["music", "âm nhạc", "(n)", "/ˈmjuː.zɪk/", "tune", "-", "Music is good for relaxing the mind.", "Âm nhạc rất tốt cho việc thư giãn trí óc.", "A1"],
  ["mistake", "lỗi sai", "(n)", "/mɪˈsteɪk/", "error; fault", "correction", "Check your test for any spelling mistake.", "Hãy kiểm tra bài kiểm tra của bạn xem có lỗi chính tả nào không.", "A2"],
  ["check", "kiểm tra", "(v)", "/tʃek/", "verify; inspect", "-", "Double-check your calculations before turning in.", "Hãy kiểm tra kỹ các phép tính của bạn trước khi nộp bài.", "A2"],
  ["spell", "đánh vần", "(v)", "/spel/", "write letters", "-", "How do you spell your first name?", "Bạn đánh vần tên của mình như thế nào?", "A1"],
  ["count", "đếm", "(v)", "/kaʊnt/", "calculate; tally", "-", "Can you count from one to one hundred?", "Bạn có thể đếm từ một đến một trăm không?", "A1"],
  ["search", "tìm kiếm", "(v/n)", "/sɜːtʃ/", "seek; look for", "lose", "Search online for the homework resources.", "Tìm kiếm trực tuyến các tài nguyên làm bài tập.", "A2"],
  ["share", "chia sẻ", "(v/n)", "/ʃeər/", "divide; distribute", "hoard", "It is polite to share your crayons.", "Chia sẻ bút màu của bạn là hành động lịch sự.", "A1"],
  ["pass", "thi đỗ", "(v)", "/pɑːs/", "clear; succeed", "fail", "I hope I will pass the grammar exam.", "Tôi hy vọng tôi sẽ thi đỗ kỳ thi ngữ pháp.", "A2"],
  ["fail", "thi trượt", "(v)", "/feɪl/", "flop", "pass", "If you don't study, you might fail.", "Nếu bạn không học, bạn có thể thi trượt.", "A2"],
  ["diploma", "bằng tốt nghiệp", "(n)", "/dɪˈpləʊ.mə/", "certificate", "-", "She received her high school diploma.", "Cô ấy đã nhận bằng tốt nghiệp trung học.", "B1"],
  ["lecture", "bài giảng", "(n/v)", "/ˈlek.tʃər/", "talk; address", "-", "The biology lecture lasted for one hour.", "Bài giảng sinh học kéo dài một tiếng.", "B1"]
];

// 3. NEW ADVANCED TOPIC: DIGITAL SOCIETY & PRIVACY (100 WORDS) - LEVEL B2-C1
const digitalWordsRaw = [
  ["algorithm", "thuật toán", "(n)", "/ˈæl.ɡə.rɪ.ðəm/", "procedure; math rule", "-", "Social media uses a complex algorithm to show posts.", "Mạng xã hội sử dụng một thuật toán phức tạp để hiển thị bài đăng.", "B2"],
  ["privacy", "quyền riêng tư", "(n)", "/ˈprɪv.ə.si/", "secrecy; solitude", "publicity", "Protect your digital privacy by hiding your info.", "Bảo vệ quyền riêng tư số bằng cách ẩn thông tin của bạn.", "B2"],
  ["security", "an ninh/bảo mật", "(n)", "/sɪˈkʊə.rə.ti/", "safety; protection", "danger; vulnerability", "A strong password improves your account security.", "Mật khẩu mạnh cải thiện tính bảo mật tài khoản của bạn.", "B2"],
  ["encryption", "sự mã hóa", "(n)", "/ɪnˈkrɪp.ʃən/", "coding; encipherment", "decryption", "End-to-end encryption keeps messages private.", "Mã hóa đầu cuối giữ cho tin nhắn được riêng tư.", "C1"],
  ["surveillance", "sự giám sát", "(n)", "/səˈveɪ.ləns/", "monitoring; observation", "privacy", "The government surveillance raises ethics questions.", "Sự giám sát của chính phủ làm nảy sinh các câu hỏi đạo đức.", "C1"],
  ["database", "cơ sở dữ liệu", "(n)", "/ˈdeɪ.tə.beɪs/", "data store", "-", "The company database stores employee profiles.", "Cơ sở dữ liệu của công ty lưu trữ hồ sơ nhân viên.", "B2"],
  ["artificial", "nhân tạo", "(adj)", "/ˌɑː.tɪˈfɪʃ.əl/", "synthetic; man-made", "natural", "Artificial light is used to grow plants indoors.", "Ánh sáng nhân tạo được dùng để trồng cây trong nhà.", "B2"],
  ["intelligence", "trí thông minh/trí tuệ", "(n)", "/ɪnˈtel.ɪ.dʒəns/", "intellect; smartness", "stupidity", "Artificial intelligence changes how we work.", "Trí tuệ nhân tạo đang thay đổi cách chúng ta làm việc.", "B2"],
  ["censorship", "sự kiểm duyệt", "(n)", "/ˈsen.sə.ʃɪp/", "control; restriction", "freedom", "Online censorship restricts access to information.", "Kiểm duyệt trực tuyến hạn chế quyền truy cập thông tin.", "C1"],
  ["broadcast", "phát sóng/truyền hình", "(v/n)", "/ˈbrɔːd.kɑːst/", "air; transmit", "-", "The news will broadcast live at six o'clock.", "Bản tin sẽ được phát sóng trực tiếp lúc sáu giờ.", "B2"],
  ["digitalize", "số hóa", "(v)", "/ˈdɪdʒ.ɪ.təl.aɪz/", "convert to digital", "-", "Libraries digitalize old books to save them.", "Các thư viện số hóa sách cổ để lưu giữ chúng.", "C1"],
  ["identity", "danh tính/bản sắc", "(n)", "/aɪˈden.tə.ti/", "individuality; self", "-", "Keep your passwords safe to prevent identity theft.", "Giữ mật khẩu an toàn để tránh bị đánh cắp danh tính.", "B2"],
  ["cyberbullying", "bắt nạt trên mạng", "(n)", "/ˌsaɪ.bəˈbʊl.i.ɪŋ/", "online harassment", "-", "Cyberbullying can cause severe emotional damage.", "Bắt nạt trên mạng có thể gây ra tổn thương tinh thần nghiêm trọng.", "B2"],
  ["harassment", "sự quấy rối/làm phiền", "(n)", "/ˈhær.əs.mənt/", "intimidation; abuse", "-", "Online harassment should be reported immediately.", "Sự quấy rối trực tuyến cần được báo cáo ngay lập tức.", "C1"],
  ["credibility", "sự uy tín/độ tin cậy", "(n)", "/ˌkred.əˈbɪl.ə.ti/", "reliability; trustworthiness", "doubtfulness", "Fake news damages the credibility of journalism.", "Tin giả hủy hoại uy tín của ngành báo chí.", "C1"],
  ["authentic", "xác thực/đích thực", "(adj)", "/ɔːˈθen.tɪk/", "genuine; real", "fake; counterfeit", "Please verify that this signature is authentic.", "Vui lòng xác minh rằng chữ ký này là thật.", "C1"],
  ["manipulate", "thao túng/điều khiển", "(v)", "/məˈnɪp.jə.leɪt/", "influence; control", "-", "Do not let social media manipulate your opinion.", "Đừng để mạng xã hội thao túng ý kiến của bạn.", "C1"],
  ["influence", "ảnh hưởng", "(v/n)", "/ˈɪn.flu.əns/", "sway; affect", "-", "Online reviews influence customer choices.", "Nhận xét trực tuyến ảnh hưởng đến sự lựa chọn của khách hàng.", "B2"],
  ["data", "dữ liệu", "(n)", "/ˈdeɪ.tə/", "information", "-", "Data privacy is a major issue in digital age.", "Bảo mật dữ liệu là vấn đề lớn trong kỷ nguyên số.", "A2"],
  ["network", "mạng lưới", "(n)", "/ˈnet.wɜːk/", "system; web", "isolation", "The computer network crashed this morning.", "Mạng máy tính bị sập vào sáng nay.", "B1"],
  ["platform", "nền tảng", "(n)", "/ˈplæt.fɔːm/", "forum; system", "-", "This platform allows creators to share videos.", "Nền tảng này cho phép người sáng tạo chia sẻ video.", "B2"],
  ["community", "cộng đồng", "(n)", "/kəˈmjuː.nə.ti/", "society; group", "-", "She joined an online community for writers.", "Cô ấy đã tham gia một cộng đồng trực tuyến dành cho các nhà văn.", "B1"],
  ["interaction", "sự tương tác", "(n)", "/ˌɪn.təˈræk.ʃən/", "communication; contact", "-", "Online education lacks face-to-face interaction.", "Giáo dục trực tuyến thiếu sự tương tác trực tiếp.", "B2"],
  ["connection", "kết nối/mối quan hệ", "(n)", "/kəˈnek.ʃən/", "link; tie", "disconnection", "I lost my internet connection during class.", "Tôi bị mất kết nối internet trong giờ học.", "A2"],
  ["communication", "truyền thông/sự giao tiếp", "(n)", "/kəˌmjuː.nɪˈkeɪ.ʃən/", "contact; exchange", "-", "Smartphones make communication very easy.", "Điện thoại thông minh làm cho việc giao tiếp rất dễ dàng.", "B1"],
  ["virtual", "ảo/thực tế ảo", "(adj)", "/ˈvɜː.tʃu.əl/", "simulated; mock", "real; physical", "We attended a virtual meeting yesterday.", "Chúng tôi đã tham dự một cuộc họp ảo vào ngày hôm qua.", "B2"],
  ["reality", "thực tế", "(n)", "/riˈæl.ə.ti/", "fact; truth", "fantasy; illusion", "We must separate digital life from reality.", "Chúng ta phải tách biệt cuộc sống ảo khỏi thực tế.", "B2"],
  ["device", "thiết bị", "(n)", "/dɪˈvaɪs/", "gadget; tool", "-", "Turn off your mobile device before sleeping.", "Hãy tắt thiết bị di động trước khi đi ngủ.", "B2"],
  ["access", "truy cập/tiếp cận", "(v/n)", "/ˈæk.ses/", "entry; enter", "deny", "You need a password to access the database.", "Bạn cần mật khẩu để truy cập cơ sở dữ liệu.", "B2"],
  ["control", "kiểm soát/điều khiển", "(v/n)", "/kənˈtrəʊl/", "manage; direct", "-", "Parents should control kids' internet usage.", "Cha mẹ nên kiểm soát việc sử dụng internet của con trẻ.", "B1"],
  ["information", "thông tin", "(n)", "/ˌɪn.fəˈmeɪ.ʃən/", "facts; data", "-", "The website displays information about courses.", "Trang web hiển thị thông tin về các khóa học.", "A2"],
  ["knowledge", "kiến thức", "(n)", "/ˈnɒl.ɪdʒ/", "understanding", "ignorance", "Sharing knowledge helps the community grow.", "Chia sẻ kiến thức giúp cộng đồng phát triển.", "A2"],
  ["trend", "xu hướng", "(n)", "/trend/", "fashion; movement", "-", "Shopping online is a growing trend.", "Mua sắm trực tuyến là một xu hướng đang phát triển.", "B1"],
  ["update", "cập nhật", "(v/n)", "/ʌpˈdeɪt/", "upgrade; modernize", "outdate", "You should update your software regularly.", "Bạn nên cập nhật phần mềm thường xuyên.", "B1"],
  ["profile", "hồ sơ cá nhân", "(n)", "/ˈprəʊ.faɪl/", "biography; account", "-", "She updated her online profile photo.", "Cô ấy đã cập nhật ảnh hồ sơ cá nhân trực tuyến.", "B1"],
  ["account", "tài khoản", "(n)", "/əˈkaʊnt/", "record; profile", "-", "I created a new email account.", "Tôi đã tạo một tài khoản thư điện tử mới.", "A2"],
  ["password", "mật khẩu", "(n)", "/ˈpɑːs.wɜːd/", "secret key", "-", "Never share your password with anyone.", "Không bao giờ chia sẻ mật khẩu với bất kỳ ai.", "A2"],
  ["hack", "xâm nhập trái phép/hacker", "(v)", "/hæk/", "penetrate", "-", "It is illegal to hack into corporate systems.", "Tấn công vào hệ thống doanh nghiệp là bất hợp pháp.", "B2"],
  ["phishing", "lừa đảo qua mạng", "(n)", "/ˈfɪʃ.ɪŋ/", "email scam", "-", "phishing emails try to steal your bank codes.", "Thư điện tử lừa đảo cố gắng lấy mã ngân hàng của bạn.", "C1"],
  ["scam", "vụ lừa đảo", "(n)", "/skæm/", "swindle; fraud", "-", "He lost money in an online investment scam.", "Anh ấy đã mất tiền trong một vụ lừa đảo đầu tư mạng.", "B2"],
  ["fraud", "sự gian lận/lừa đảo", "(n)", "/frɔːd/", "deception; cheat", "honesty", "Credit card fraud is on the rise.", "Gian lận thẻ tín dụng đang gia tăng.", "C1"],
  ["piracy", "vi phạm bản quyền", "(n)", "/ˈpaɪ.rə.si/", "copyright theft", "-", "Software piracy harms the IT industry.", "Vi phạm bản quyền phần mềm gây hại cho ngành CNTT.", "C1"],
  ["copyright", "bản quyền", "(n/v)", "/ˈkɒp.i.raɪt/", "intellectual property", "-", "Ensure you do not violate the copyright laws.", "Hãy chắc chắn rằng bạn không vi phạm luật bản quyền.", "B2"],
  ["license", "giấy phép", "(n/v)", "/ˈlaɪ.səns/", "permit; authorization", "forbid", "You need a software license to use it.", "Bạn cần có giấy phép phần mềm để sử dụng nó.", "B2"],
  ["software", "phần mềm", "(n)", "/ˈsɒft.weər/", "computer program", "hardware", "Install this software to protect your system.", "Hãy cài đặt phần mềm này để bảo vệ hệ thống.", "B1"],
  ["hardware", "phần cứng", "(n)", "/ˈhɑːd.weər/", "physical parts", "software", "We bought new hardware for the computer lab.", "Chúng tôi đã mua phần cứng mới cho phòng máy tính.", "B2"],
  ["system", "hệ thống", "(n)", "/ˈsɪs.təm/", "network; structure", "-", "The library system is simple to use.", "Hệ thống thư viện rất dễ sử dụng.", "A2"],
  ["server", "máy chủ", "(n)", "/ˈsɜː.vər/", "host computer", "-", "The web server went offline for maintenance.", "Máy chủ web đã ngoại tuyến để bảo trì.", "B2"],
  ["cloud", "điện toán đám mây", "(n)", "/klaʊd/", "cloud computing", "-", "I save my backup files in the cloud.", "Tôi lưu trữ các tệp sao lưu của mình trên đám mây.", "B2"],
  ["storage", "lưu trữ/dung lượng", "(n)", "/ˈstɔː.rɪdʒ/", "holding; warehouse", "-", "This phone has 128 GB of internal storage.", "Điện thoại này có dung lượng lưu trữ trong 128 GB.", "B2"],
  ["backup", "sao lưu/dự phòng", "(n/v)", "/ˈbæk.ʌp/", "reserve; safeguard", "-", "Always keep a backup of your master data.", "Luôn luôn giữ bản sao lưu dữ liệu gốc của bạn.", "B2"],
  ["download", "tải xuống", "(v/n)", "/ˌdaʊnˈləʊd/", "save; fetch", "upload", "You can download the textbook for free.", "Bạn có thể tải sách giáo khoa xuống miễn phí.", "A2"],
  ["upload", "tải lên", "(v/n)", "/ˌʌpˈləʊd/", "post; transfer", "download", "It took ten minutes to upload the video.", "Mất mười phút để tải video lên.", "A2"],
  ["install", "cài đặt", "(v)", "/ɪnˈstɔːl/", "set up; place", "uninstall", "Please install the update immediately.", "Vui lòng cài đặt bản cập nhật ngay lập tức.", "B1"],
  ["delete", "xóa", "(v)", "/dɪˈliːt/", "erase; remove", "insert; keep", "You can delete these temporary files now.", "Bạn có thể xóa những tệp tạm thời này ngay.", "A2"],
  ["search", "tìm kiếm", "(v/n)", "/sɜːtʃ/", "seek; look up", "-", "I will search for the legal terms.", "Tôi sẽ tìm kiếm các điều khoản pháp lý.", "A2"],
  ["filter", "lọc/bộ lọc", "(v/n)", "/ˈfɪl.tər/", "strainer; screen", "-", "You can filter search results by date.", "Bạn có thể lọc kết quả tìm kiếm theo ngày.", "B2"],
  ["block", "chặn", "(v/n)", "/blɒk/", "stop; obstruct", "allow", "You should block spam emails.", "Bạn nên chặn các thư điện tử rác.", "B1"],
  ["report", "báo cáo", "(v/n)", "/rɪˈpɔːt/", "announce; declare", "-", "Report any security breach to the IT team.", "Báo cáo bất kỳ sự cố bảo mật nào cho đội CNTT.", "B1"],
  ["cookies", "tệp lưu thông tin duyệt web", "(n)", "/ˈkʊk.iz/", "web data tracker", "-", "Accept cookies to customize your experience.", "Chấp nhận cookie để tùy chỉnh trải nghiệm của bạn.", "B2"],
  ["cache", "bộ nhớ đệm", "(n/v)", "/kæʃ/", "temporary store", "-", "Clear your browser cache to reload the site.", "Xóa bộ nhớ đệm trình duyệt để tải lại trang.", "C1"],
  ["browser", "trình duyệt", "(n)", "/ˈbraʊ.zər/", "web client", "-", "Which web browser do you prefer to use?", "Bạn thích sử dụng trình duyệt web nào hơn?", "B1"],
  ["website", "trang web", "(n)", "/ˈweb.saɪt/", "webpage", "-", "Visit our official website for more details.", "Hãy ghé thăm trang web chính thức để biết thêm chi tiết.", "A2"],
  ["domain", "tên miền/phạm vi", "(n)", "/dəʊˈmeɪn/", "field; realm", "-", "The domain registration will expire soon.", "Đăng ký tên miền sẽ sớm hết hạn.", "B2"],
  ["link", "đường dẫn/kết nối", "(n/v)", "/lɪŋk/", "connection; URL", "-", "Click on the link to watch the tutorial.", "Nhấp vào đường dẫn để xem hướng dẫn.", "A2"],
  ["signal", "tín hiệu/sóng", "(n/v)", "/ˈsɪɡ.nəl/", "sign; indicator", "-", "The mobile signal is very weak here.", "Sóng di động ở đây rất yếu.", "B1"],
  ["speed", "tốc độ", "(n/v)", "/spiːd/", "velocity; pace", "slowness", "Fiber internet has incredible connection speed.", "Internet cáp quang có tốc độ kết nối đáng kinh ngạc.", "A2"],
  ["Wi-Fi", "mạng không dây", "(n)", "/ˈwaɪ.faɪ/", "wireless connection", "-", "Is there free Wi-Fi in this coffee shop?", "Ở quán cà phê này có Wi-Fi miễn phí không?", "A1"],
  ["online", "trực tuyến", "(adj/adv)", "/ˌɒnˈlaɪn/", "web-based; connected", "offline", "I do my banking online.", "Tôi thực hiện giao dịch ngân hàng trực tuyến.", "A2"],
  ["offline", "ngoại tuyến", "(adj/adv)", "/ˌɒfˈlaɪn/", "disconnected", "online", "The database is currently offline.", "Cơ sở dữ liệu hiện đang ngoại tuyến.", "A2"],
  ["screen", "màn hình", "(n)", "/skriːn/", "display; monitor", "-", "I bought a larger computer screen.", "Tôi đã mua một màn hình máy tính lớn hơn.", "A1"],
  ["keyboard", "bàn phím", "(n)", "/ˈkiː.bɔːd/", "keys panel", "-", "He cleaned the dust from the keyboard.", "Anh ấy đã lau bụi khỏi bàn phím.", "A1"],
  ["mouse", "chuột máy tính", "(n)", "/maʊs/", "cursor controller", "-", "The wireless mouse needs new batteries.", "Chuột không dây cần pin mới.", "A1"],
  ["headphone", "tai nghe", "(n)", "/ˈhed.fəʊn/", "earphone", "-", "Put on your headphone for the listening test.", "Đeo tai nghe của bạn để làm bài kiểm tra nghe.", "A2"],
  ["microphone", "micrô", "(n)", "/ˈmaɪ.krə.fəʊn/", "mic", "-", "Speak into the microphone clearly.", "Hãy nói rõ vào micrô.", "A2"],
  ["camera", "máy ảnh/webcam", "(n)", "/ˈkæm.rə/", "video recorder", "-", "Turn on your camera for the virtual class.", "Bật máy ảnh của bạn cho lớp học ảo.", "A1"],
  ["app", "ứng dụng", "(n)", "/æp/", "application; program", "-", "I downloaded a language learning app.", "Tôi đã tải xuống một ứng dụng học ngôn ngữ.", "A2"],
  ["tool", "công cụ", "(n)", "/tuːl/", "instrument; utility", "-", "A dictionary is a useful tool for learners.", "Từ điển là một công cụ hữu ích cho người học.", "A2"],
  ["function", "chức năng", "(n/v)", "/ˈfʌŋk.ʃən/", "purpose; operation", "-", "The main function of this software is backup.", "Chức năng chính của phần mềm này là sao lưu.", "B2"],
  ["option", "lựa chọn", "(n)", "/ˈɒp.ʃən/", "choice; alternative", "-", "You have the option to skip this exercise.", "Bạn có lựa chọn bỏ qua bài tập này.", "A2"],
  ["setting", "cài đặt/thiết lập", "(n)", "/ˈset.ɪŋ/", "configuration", "-", "You can change language settings in control panel.", "Bạn có thể thay đổi cài đặt ngôn ngữ trong bảng điều khiển.", "B1"],
  ["mode", "chế độ", "(n)", "/məʊd/", "state; setting", "-", "Use dark mode to save battery.", "Sử dụng chế độ tối để tiết kiệm pin.", "B2"],
  ["notification", "thông báo", "(n)", "/ˌnəʊ.tɪ.fɪˈkeɪ.ʃən/", "alert; warning", "-", "You will receive a notification when it's done.", "Bạn sẽ nhận được thông báo khi hoàn thành.", "B2"],
  ["message", "tin nhắn", "(n/v)", "/ˈmes.ɪdʒ/", "note; text", "-", "Send me a message when you arrive.", "Gửi cho tôi một tin nhắn khi bạn đến nơi.", "A1"],
  ["email", "thư điện tử", "(n/v)", "/ˈiː.meɪl/", "electronic mail", "-", "I received an email from my principal.", "Tôi đã nhận được một thư điện tử từ hiệu trưởng.", "A1"],
  ["send", "gửi", "(v)", "/send/", "mail; dispatch", "receive", "I will send you the project slides tonight.", "Tôi sẽ gửi cho bạn các trang trình bày dự án tối nay.", "A1"],
  ["receive", "nhận", "(v)", "/rɪˈsiːv/", "get; accept", "send", "Did you receive my last message?", "Bạn đã nhận được tin nhắn cuối cùng của tôi chưa?", "A1"],
  ["forward", "chuyển tiếp", "(v)", "/ˈfɔː.wəd/", "pass on; redirect", "-", "Please forward the file to the entire group.", "Vui lòng chuyển tiếp tệp tin cho cả nhóm.", "B1"],
  ["reply", "trả lời", "(v/n)", "/rɪˈplaɪ/", "answer; respond", "ignore", "I will reply to your email tomorrow.", "Tôi sẽ trả lời thư điện tử của bạn vào ngày mai.", "A2"],
  ["attach", "đính kèm", "(v)", "/əˈtætʃ/", "connect; append", "detach", "Remember to attach your diploma copy.", "Nhớ đính kèm bản sao bằng tốt nghiệp của bạn.", "B2"],
  ["file", "tệp tin/hồ sơ", "(n/v)", "/faɪl/", "document; record", "-", "Save the text file to your documents folder.", "Lưu tệp văn bản vào thư mục tài liệu của bạn.", "A2"],
  ["folder", "thư mục", "(n)", "/ˈfəʊl.dər/", "directory", "-", "Create a new folder for science projects.", "Tạo một thư mục mới cho các dự án khoa học.", "A2"],
  ["trash", "thùng rác", "(n/v)", "/træʃ/", "garbage; recycle bin", "-", "Drag the unwanted file into the trash.", "Kéo tệp không mong muốn vào thùng rác.", "A2"],
  ["firewall", "tường lửa", "(n)", "/ˈfaɪə.wɔːl/", "security shield", "-", "The firewall blocks unauthorized network traffic.", "Tường lửa chặn lưu lượng mạng không được phép.", "B2"],
  ["bandwidth", "băng thông", "(n)", "/ˈbænd.wɪtθ/", "transmission capacity", "-", "Video calls require high bandwidth.", "Các cuộc gọi video yêu cầu băng thông cao.", "C1"],
  ["malware", "phần mềm độc hại", "(n)", "/ˈmæl.weər/", "malicious software", "-", "Scan your PC regularly to remove malware.", "Quét máy tính thường xuyên để loại bỏ phần mềm độc hại.", "C1"],
  ["protocol", "giao thức/quy tắc", "(n)", "/ˈprəʊ.tə.kɒl/", "set of rules; code", "-", "HTTPS is a secure web protocol.", "HTTPS là một giao thức web an toàn.", "C1"],
  ["sync", "đồng bộ hóa", "(v/n)", "/sɪŋk/", "synchronize; match", "-", "Your data will sync automatically across devices.", "Dữ liệu của bạn sẽ tự động đồng bộ hóa trên các thiết bị.", "B2"],
  ["disconnect", "ngắt kết nối", "(v/n)", "/ˌdɪs.kəˈnekt/", "sever; detach", "connect", "Disconnect the USB drive safely.", "Ngắt kết nối ổ USB một cách an toàn.", "B1"],
  ["subscribe", "đăng ký/theo dõi", "(v)", "/səbˈskraɪb/", "follow; register", "unsubscribe", "Subscribe to our channel for weekly videos.", "Hãy đăng ký kênh của chúng tôi để xem video hàng tuần.", "B1"]
];

const compileWords = (rawArray) => {
  return rawArray.map((row) => {
    const [en, vi, type, ipa, syn, ant, example, viExample, level] = row;
    return {
      en,
      vi,
      type,
      ipa,
      example,
      viExample,
      synonyms: syn !== '-' ? syn : '',
      antonyms: ant !== '-' ? ant : '',
      level
    };
  });
};

const wordsSuccess = compileWords(successWordsRaw);
const wordsSchool = compileWords(schoolWordsRaw);
const wordsDigital = compileWords(digitalWordsRaw);

// Stories
const storySuccessEn = "To achieve your goal and reach success, you must put in effort and find motivation. You can inspire others when you overcome every obstacle with determination. Keep your focus, develop a growth mindset, and build a good habit. Consistency and discipline will lead to resilience. Make progress daily, unlock your potential, execute your strategy, and follow your vision with ambition and courage. Your dedication will empower you to be fearless and grateful. Embrace hardship, innovate, and enjoy the journey of knowledge, leadership, and mastery. Navigate with optimism, passion, and quality. Reflect on your skill, talent, and unique value. Use your wisdom, yield good results, and act with zeal.";
const storySuccessVi = "Để đạt được mục tiêu và đến với thành công, bạn phải nỗ lực và tìm thấy động lực. Bạn có thể truyền cảm hứng cho người khác khi vượt qua mọi trở ngại với sự quyết tâm. Giữ tập trung, phát triển tư duy, và xây dựng thói quen tốt. Sự kiên định và kỷ luật sẽ dẫn đến sự kiên cường. Tạo ra tiến bộ mỗi ngày, mở khóa tiềm năng, thực thi chiến lược, và theo đuổi tầm nhìn với hoài bão và lòng dũng cảm. Sự cống hiến sẽ trao quyền cho bạn không sợ hãi và luôn biết ơn. Đón nhận sự gian khổ, đổi mới, và tận hưởng hành trình của kiến thức, sự lãnh đạo, và sự thành thạo. Điều hướng với sự lạc quan, đam mê, và chất lượng. Ngẫm nghĩ về kỹ năng, tài năng, và giá trị độc đáo của bạn. Dùng trí tuệ, mang lại kết quả tốt, và hành động với sự nhiệt huyết.";

const storySchoolEn = "A hard-working student packs their notebook, pencil, ruler, and eraser in their schoolbag every morning. In the classroom, the teacher uses a whiteboard and a map during the history lesson. The classmates write questions and answers, and use a dictionary to learn new English words. During the break, they play in the playground and chat. After school, students complete their homework, review their lessons, and prepare projects to pass their exams, showing they are smart and clever.";
const storySchoolVi = "Một học sinh chăm chỉ cất vở, bút chì, thước kẻ và cục tẩy vào cặp sách mỗi sáng. Trong lớp học, giáo viên sử dụng bảng trắng và bản đồ trong bài học lịch sử. Các bạn cùng lớp viết câu hỏi và câu trả lời, đồng thời sử dụng từ điển để học từ tiếng Anh mới. Trong giờ giải lao, họ chơi đùa trên sân chơi và trò chuyện. Sau giờ học, học sinh hoàn thành bài tập về nhà, ôn tập bài học và chuẩn bị dự án để thi đỗ, chứng tỏ họ là người thông minh và lanh lợi.";

const storyDigitalEn = "In our digital society, computer security and personal privacy depend heavily on encryption algorithms. When accessing a database server, we must protect our identity against online fraud, scams, and cyberbullying. Users should control their password settings, enable firewalls, backup data in the cloud, and install software updates to prevent database hacking, phishing, and malware threats, ensuring a secure internet connection.";
const storyDigitalVi = "Trong xã hội số của chúng ta, bảo mật máy tính và quyền riêng tư cá nhân phụ thuộc lớn vào các thuật toán mã hóa. Khi truy cập máy chủ cơ sở dữ liệu, chúng ta phải bảo vệ danh tính của mình trước các hành vi gian lận trực tuyến, lừa đảo và bắt nạt trên mạng. Người dùng nên kiểm soát cài đặt mật khẩu của mình, bật tường lửa, sao lưu dữ liệu trên đám mây và cài đặt các bản cập nhật phần mềm để ngăn chặn việc xâm nhập cơ sở dữ liệu, lừa đảo qua mạng và các mối đe dọa từ phần mềm độc hại, đảm bảo kết nối internet an toàn.";

const fileContent = `// File: src/data/vocabExtraData2.js
// Generated programmatically with 3 topics of exactly 100 words each.

export const vocabExtraData2 = [
  {
    id: "success-mindset-100",
    title: "🌟 Thành Công & Phát Triển Bản Thân (100 Từ) (B1-C1)",
    description: "Bộ 100 từ vựng đỉnh cao về phát triển bản thân, tư duy lãnh đạo. Đầy đủ từ đồng nghĩa, trái nghĩa, siêu hay cho IELTS & TOEIC!",
    level: "B1-C1",
    examTags: ["IELTS Band 6+", "TOEIC 700+", "Life"],
    words: ${JSON.stringify(wordsSuccess, null, 2)},
    storyEn: ${JSON.stringify(storySuccessEn)},
    storyVi: ${JSON.stringify(storySuccessVi)},
  },
  {
    id: "school-life-100",
    title: "🏫 Đời Sống Học Đường & Vật Dụng (100 Từ) (A1-A2)",
    description: "100 từ vựng nền tảng cực kỳ quen thuộc về học tập, lớp học, dụng cụ học tập và giao tiếp cơ bản tại trường lớp.",
    level: "A1-A2",
    examTags: ["Basic", "Kids", "Daily"],
    words: ${JSON.stringify(wordsSchool, null, 2)},
    storyEn: ${JSON.stringify(storySchoolEn)},
    storyVi: ${JSON.stringify(storySchoolVi)},
  },
  {
    id: "digital-society-100",
    title: "🌐 Xã Hội Số & Quyền Riêng Tư (100 Từ) (B2-C1)",
    description: "100 từ vựng nâng cao cực hay về công nghệ, internet, an toàn thông tin, bảo mật và tương tác xã hội trong kỷ nguyên số.",
    level: "B2-C1",
    examTags: ["IELTS Band 6.5+", "Tech", "Society"],
    words: ${JSON.stringify(wordsDigital, null, 2)},
    storyEn: ${JSON.stringify(storyDigitalEn)},
    storyVi: ${JSON.stringify(storyDigitalVi)},
  }
];

export default vocabExtraData2;
`;

fs.writeFileSync(filePath, fileContent, 'utf8');
console.log('Successfully generated vocabExtraData2.js with three 100-word topics!');
