# Extract IELTS PREP.zip into public/ielts-prep/ (flattened, ASCII folder names)
# and emit src/data/ieltsPrepData.js — a manifest of PDFs (per-file lessons) and
# PNG galleries, used by IeltsFoundationPage as the "Tài liệu Band 7+" chặng.
import zipfile, os, io, re
from urllib.parse import quote

ZIP = r'C:/Users/Huynh Ngoc Mai/Downloads/IELTS PREP.zip'
ROOT = r'd:/HocCode/grammar-app'
OUT_DIR = os.path.join(ROOT, 'public', 'ielts-prep')

# map original sub-folder (basename) -> (asciiFolder, courseTitle, kind)
# kind: 'pdf' = one lesson per PDF; 'gallery' = one lesson holding all images
FOLDER_MAP = {
    '30 Chủ điểm ngữ pháp quan trọng': ('grammar', '30 Chủ điểm Ngữ pháp quan trọng', 'pdf'),
    'I - TỪ VỰNG + BÀI MÃU SPEAKING': ('speaking', 'Từ vựng & Bài mẫu Speaking (theo chủ đề)', 'pdf'),
    'II - TỪ VỰNG WRITING': ('writing', 'Từ vựng Writing', 'pdf'),
    'III - TỪ VỰNG LISTENING': ('listening', 'Từ vựng Listening', 'pdf'),
    'IV - Cặp từ vựng gây lú': ('pairs', 'Cặp từ vựng dễ nhầm (thẻ hình)', 'gallery'),
    'Tổng hợp 200 chủ đề từ vựng IELTS BAND 7+': ('topics200', '200 chủ đề Từ vựng Band 7+ (thẻ hình)', 'gallery'),
    '0. FILE LỘ TRÌNH HỌC': ('roadmap-files', 'File lộ trình học (Excel)', 'file'),
}

def lead_num(name):
    m = re.match(r'\s*(\d+)', name)
    return int(m.group(1)) if m else 9999

z = zipfile.ZipFile(ZIP)
# collect files per mapped folder
collected = {k: [] for k in FOLDER_MAP}
for n in z.namelist():
    if n.endswith('/'):
        continue
    parts = [p for p in n.split('/') if p]
    # parts[0] = 'IELTS PREP (...)'; find a mapped folder anywhere in the path
    folder = None
    for p in parts:
        if p in FOLDER_MAP:
            folder = p
            break
    if folder is None:
        continue
    collected[folder].append(n)

os.makedirs(OUT_DIR, exist_ok=True)
courses = []
for orig, (ascii_folder, title, kind) in FOLDER_MAP.items():
    files = collected.get(orig, [])
    if not files:
        continue
    dest = os.path.join(OUT_DIR, ascii_folder)
    os.makedirs(dest, exist_ok=True)
    saved = []  # (filename, ext)
    for n in files:
        fname = os.path.basename(n)
        ext = os.path.splitext(fname)[1].lower()
        with z.open(n) as src, open(os.path.join(dest, fname), 'wb') as out:
            out.write(src.read())
        saved.append((fname, ext))
    # build lessons
    lessons = []
    if kind == 'pdf' or kind == 'file':
        for fname, ext in sorted(saved, key=lambda x: (lead_num(x[0]), x[0])):
            url = 'ielts-prep/%s/%s' % (ascii_folder, quote(fname))
            title_l = os.path.splitext(fname)[0]
            key = 'pdfs' if ext == '.pdf' else 'docs'
            lessons.append({'title': title_l, key: [{'title': title_l, 'src': url}]})
    else:  # gallery
        imgs = [ {'title': os.path.splitext(f)[0], 'src': 'ielts-prep/%s/%s' % (ascii_folder, quote(f))}
                 for f, e in sorted(saved, key=lambda x: (lead_num(x[0]), x[0])) if e == '.png' ]
        lessons.append({'title': '%s (%d thẻ)' % (title, len(imgs)), 'images': imgs})
    courses.append({'id': 'prep-' + ascii_folder, 'title': title,
                    'tag': ('%d tài liệu' % len(lessons)) if kind != 'gallery' else ('%d thẻ hình' % len(saved)),
                    'lessons': lessons})

# emit JS
import json
def js(o): return json.dumps(o, ensure_ascii=False, indent=2)
body = 'const ieltsPrepData = ' + js(courses) + ';\n\nexport default ieltsPrepData;\n'
header = ('// AUTO-GENERATED by scratch/extract_ielts_prep.py — do not edit by hand.\n'
          '// PDF & image study materials from "IELTS PREP.zip" (grammar topics, IELTS\n'
          '// Band 7+ vocabulary by topic, Speaking/Writing/Listening vocab). Served from\n'
          '// public/ielts-prep (gitignored). Rendered as the "Tài liệu Band 7+" chặng.\n\n')
io.open(os.path.join(ROOT, 'src', 'data', 'ieltsPrepData.js'), 'w', encoding='utf-8', newline='').write(header + body)
print('courses:', len(courses), '| total files extracted:', sum(len(collected[k]) for k in collected))
for c in courses:
    print('  %-40s %d lessons' % (c['title'][:40], len(c['lessons'])))
